kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: v101
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
